spring:
  application:
    name: gymapp-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    serviceUrl:
      defaultZone: http://gymapp-eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8888
